shared: &shared
  - ".nvmrc"
  - ".ci"
  - ".github/**"
docker:
  - *shared
  - Dockerfile
rust:
  - *shared
  - ".cargo/**"
  - "backend-end/**"
  - Cargo.lock
  - "*.toml"
typescript:
  - *shared
  - "front-end/**"
  - "**/*.ts"
  - "**/*.cjs"
  - "package.json"
  - "package-lock.json"
