[package]
name = "endless-ssh-rs"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.75.0"
authors = ["Kristof Mattei"]
description = "endless-ssh-rs"
license-file = "LICENSE"
categories = ["ssh", "utility"]
keywords = ["ssh", "tarpit", "script-kiddies"]
repository = "https://github.com/kristof-mattei/endless-ssh-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
coverage = []

[dependencies]
color-eyre = "0.6.2"
clap = { version = "4.4.16", features = ["cargo"] }
libc = "0.2.152"
lazy_static = "1.4.0"
mockall = "0.12.1"
mockall_double = "0.3.1"
rand = "0.8.5"
time = { version = "0.3.31", features = ["formatting"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "time",
    "tracing-log",
] }

# We compile the Docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]
# openssl = { version = "0.10.36", features = ["vendored"] }
