[package]
name = "endless-ssh-rs"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.62.0"
authors = ["Kristof Mattei"]
description = "endless-ssh-rs"
license-file = "LICENSE"
categories = ["ssh", "hacker"]
keywords = ["ssh", "hacker"]
repository = "https://github.com/kristof-mattei/endless-ssh-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
coverage = []

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.10", features = ["cargo"] }
libc = "0.2.126"
rand = "0.8.5"
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
# reqwest = { version = "0.11.5", features = ["json"] }
# serde_json = "1.0.68"
# serde = { version = "1.0.130", features = ["derive"] }
# futures = "0.3.17"
# tokio = { version = "1.12.0", features = ["full"] }
# log = "0.4.14"
# env_logger = "0.9.0"
# serde_yaml = "0.8.21"
# clap = { version = "3.0.14", features = ["derive"] }

# We compile the Docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]
# openssl = { version = "0.10.36", features = ["vendored"] }
