[package]
name = "endless-ssh-rs"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.79.0"
authors = ["Kristof Mattei"]
description = "endless-ssh-rs"
license-file = "LICENSE"
categories = ["ssh", "utility"]
keywords = ["ssh", "tarpit", "skipt-kiddies"]
repository = "https://github.com/kristof-mattei/endless-ssh-rs"

[[bin]]
name = "endless-ssh-rs"
path = "back-end/src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
# don't stop from compiling / running
all = "warn"
pedantic = "warn"
cargo = "warn"
# this one causes confusion when combining variables (`foo`) and
# dereferenced variables (`foo.bar`). The latter cannot be inlined
# so we don't inline anything
uninlined-format-args = { level = "allow", priority = 127 }

[lints.rust]
let_underscore_drop = { level = "deny", priority = 127 }
non_ascii_idents = { level = "deny", priority = 127 }

[profile.dev.package.backtrace]
opt-level = 3

[[test]]
name = "endless-ssh-rs"
path = "back-end/tests/integration_tests.rs"

[features]
coverage = []

[dependencies]
axum = { version = "0.7.5" }
backtrace = "0.3.73"
clap = { version = "4.5.8", features = ["cargo"] }
color-eyre = { git = "https://github.com/kristof-mattei/eyre", branch = "bump-backtrace-rs", features = [
    "track-caller",
] }
dotenvy = "0.15.7"
libc = "0.2.154"
mockall = "0.12.1"
mockall_double = "0.3.1"
once_cell = "1.19.0"
rand = "0.8.5"
reverse-proxy-service = { git = "https://github.com/manorom/reverse-proxy-service", rev = "fda8bf28b4c602bdcf5f941b584e3e4940a1491e", features = [
    "axum",
] }
socketioxide = { version = "0.14.0", features = ["tracing"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"
time = { version = "0.3.36", features = ["formatting"] }
tokio = { version = "1.38.0", features = [
    "io-util",
    "io-std",
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-util = "0.7.11"
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["cors", "fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "time",
    "tracing-log",
] }
tracing-error = "0.2.0"
url = { version = "2.5.2", features = ["serde"] }

# [dev-dependencies]
# stubr = "0.6.2"

# We compile the Docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
