[package]
name = "endless-ssh-rs"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.79.0"
authors = ["Kristof Mattei"]
description = "endless-ssh-rs"
license-file = "LICENSE"
categories = ["ssh", "utility"]
keywords = ["ssh", "tarpit", "script-kiddies"]
repository = "https://github.com/kristof-mattei/endless-ssh-rs"

[lints.clippy]
# don't stop from compiling / running
all = "warn"
pedantic = "warn"
cargo = "warn"
# this one causes confusion when combining variables (`foo`) and
# dereferenced variables (`foo.bar`). The latter cannot be inlined
# so we don't inline anything
uninlined-format-args = { level = "allow", priority = 127 }

[lints.rust]
let_underscore_drop = { level = "deny", priority = 127 }
non_ascii_idents = { level = "deny", priority = 127 }

[profile.dev.package.backtrace]
opt-level = 3

[features]
coverage = []

[dependencies]
clap = { version = "4.5.11", features = ["cargo"] }
color-eyre = { git = "https://github.com/eyre-rs/eyre", rev = "2dc0688d33a487009e8bc3222cbab135261383b0", features = [
    "track-caller",
] }
dotenvy = "0.15.7"
libc = "0.2.154"
mockall = "0.13.0"
mockall_double = "0.3.1"
once_cell = "1.19.0"
rand = "0.8.5"
time = { version = "0.3.36", features = ["formatting"] }
tokio = { version = "1.39.1", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "signal",
    "net",
    "sync",
    "io-util",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "time",
    "tracing-log",
] }
tracing-error = "0.2.0"
tokio-util = "0.7.11"

# We compile the Docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]
# openssl = { version = "0.10.36", features = ["vendored"] }
