name: Update semantic tags on repo & image after release

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false # last one must win in case of multiple releases

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  packages: write

jobs:
  move-git-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        shell: bash
        run: |
          npm ci --ignore-scripts

      - name: Split the incoming tag into major, minor and patch
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          # because in the JS github variable ref_name isn't there
          TAGNAME: ${{ github.ref_name }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const semver = require("semver");

            // parse our version
            let parsed = semver.parse(process.env.TAGNAME);

            core.exportVariable("MAJOR", parsed.major);
            core.exportVariable("MINOR", parsed.minor);
            core.exportVariable("PATCH", parsed.patch);

      - name: Move v${{ env.MAJOR }} and v${{ env.MAJOR }}.${{ env.MINOR }} tags
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { serializeError } = core.isDebug() ? require("serialize-error") : { serializeError: () => {} };

            const tagsToMove = [
                // already covered by semantic-release, it is what triggers this WF
                // `v${process.env.MAJOR}.${process.env.MINOR}.${process.env.PATCH}`,
                `v${process.env.MAJOR}.${process.env.MINOR}`,
                // only do major if we're off v0, as v0 is the semver exception
                ...(0 !== process.env.MAJOR ? [`v${process.env.MAJOR}`] : [])
            ];

            core.info(`Trying to move the following tags: ${tagsToMove.join(", ")} by deleting and re-creating.`);

            async function move(tag) {
                const ref = {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `tags/${tag}`
                };

                try {
                    await github.rest.git.deleteRef({
                        ...ref,
                    });

                    core.info(`Deleted ${tag}.`);
                } catch (e) {
                    core.info(`The tag ${tag} doesn't exist yet, that's OK, it happens on new versions.`);
                    core.debug(serializeError(e));
                }

                try {
                    await github.rest.git.createRef({
                        ...ref,
                        // to delete a tag with deleteRef the format of the ref is tags/{tag}
                        // to create a tag with createRef the format of the ref is /refs/tags/{tag}
                        // # confused
                        ref: `refs/${ref.ref}`,
                        sha: context.sha
                    });

                    core.info(`Created ${tag} on ${context.sha}.`);

                } catch (e) {
                    core.setFailed(`Failed to create tag ${tag}.`);
                    core.debug(serializeError(e));
                }
            }

            await Promise.all(tagsToMove.map(move));

            core.info("All done!");

  retag-containers:
    name: Retag the containers
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        shell: bash
        run: |
          npm ci --ignore-scripts

      - name: Download crane tar, extract, and add folder to path.
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const tc = require("@actions/tool-cache");

            const release = await github.rest.repos.getLatestRelease({
                owner: "google",
                repo: "go-containerregistry"
            });

            const asset = release.data.assets.find(asset => {
                return asset["content_type"] === "application/gzip" && asset.name === "go-containerregistry_Linux_x86_64.tar.gz";
            });

            const urlToCraneTar = asset.browser_download_url

            const craneTarPath = await tc.downloadTool(urlToCraneTar);
            const craneExtractedFolder = await tc.extractTar(craneTarPath, null, ["--extract", "--gzip"]);

            core.addPath(craneExtractedFolder);

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set full image name
        shell: bash
        run: |

          echo "FULL_IMAGE_NAME=${REGISTRY,,}/${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Find all tags for ${{ env.FULL_IMAGE_NAME }}
        shell: bash
        run: |

          crane ls ${FULL_IMAGE_NAME} >> existing_tags

          echo "These are the existing tags on ${FULL_IMAGE_NAME}:"
          cat existing_tags

      - name: Check if the incoming PR has a Docker container, which will be our old tag
        shell: bash
        run: |
          old_tag=$(cat existing_tags | grep "^sha-${{ github.sha }}-.*\$") # .* is actual or retag

          echo "OLD_TAG=${old_tag}" >> ${GITHUB_ENV}

      - name: Set the new TAGs
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # v4.4.0
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=raw,value=latest
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.0.') }}
            type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Actually re-tag the container
        shell: bash
        run: |
          echo "${{ steps.meta.outputs.tags }}" | while read new_tag
          do
            crane cp "${FULL_IMAGE_NAME}:${OLD_TAG}" ${new_tag}
          done
