name: Test Release (do a dry run)

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch: # releasing is manual as we don't want to release every time
    inputs:
      name:
        description: World?
        required: false
        default: "Hello World!"

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Only on main
        if: ${{ github.ref != 'refs/heads/main' }}
        shell: bash
        run: |
          echo "Only to be executed on main"
          exit 1

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup Node.js
        uses: actions/setup-node@e954e154314f6a50ae79ea6c1c369b1f340307ff
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        shell: bash
        run: |
          npm ci --ignore-scripts

      - name: Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::group::Release dry run output"
          npm run release -- --dry-run
          echo "::endgroup::"
